### ISSUE TITLE
No music in title screen / very quiet music in game

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#1]
No music in title screen / very quiet music in game despite max volume settings.

**Comment by slashman** [comment]
This is for v0.25.2 only? and you also mentioned SFX are fine at full volume. Does this persist after restarting the game?

**Comment by Kaytila** [comment]
So I understand now where this is coming from  - I have my PC sound volume at around 20% at times.
The music in the title sceen is somehow more affected by this than the sound effects, meaning that the effects were audible, the music was not.
After I turned up my general PC sound volume to 60% again, I can hear the music again in the title screen.

In-Game, it was always audible.

Not sure whether this is a driver issue, a hardware topic, an OS topic, or my hearing.

**Comment by slashman** [comment]
I think this is probably an issue with the default volume applied to music vs sfx, should probably be 100% and have the player equalize using the bars. Will talk with the soundman.

**Comment by slashman** [comment]
I'm wondering if this is just an issue with the volume of the title screen music

**Comment by Stoltverd** [comment]
Can't be reproduced.
