### ISSUE TITLE
combat encounter - still meeting spanish archer

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#13]
still meeting a spanish archer. i thought all of these should be replaced by crossbowmen?
<img width="796" alt="2021-05-20 17_51_18-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119010104-02e82a00-b994-11eb-9443-68e17d8bce33.png">

**Comment by Kaytila** [comment]
I guess that depends on whether hunting bows were still in use back then - if they were, then sure, keep them. I was obviously mixing up military and civilian people.
Though would there have been civilian spanish archers in that area?

**Comment by slashman** [comment]
Fixed for 0.26.3+
