### ISSUE TITLE
banter popups break UI

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#15]
banter popping up to the lower left will do the following two things:

it will block the ui buttons to the lower right from functioning
if you use shortcuts, these work (i.e. J), but you cannot close the Journal anymore before you click the banter away.
You can still navigate over the map, however.
<img width="1859" alt="2021-05-20 18_10_07-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119012950-ca961b00-b996-11eb-9915-7fd90f96b1cc.png">

**Comment by Kaytila** [comment]
banter popping up to the lower left will do the following two things:

1. it will block the ui buttons to the lower right from functioning
2. if you use shortcuts, these work (i.e. J), but you cannot close the Journal anymore before you click the banter away.

You can still navigate over the map, however.
<img width="1859" alt="2021-05-20 18_10_07-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119012817-aa665c00-b996-11eb-99fe-5839281d7f4b.png">

**Comment by slashman** [comment]
Seems to only happen for loaded games?

**Comment by slashman** [comment]
Fixed for v0.26.1
