### ISSUE TITLE
Dev Console - close does not work

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#17]
Dev Console - close does not work

**Comment by slashman** [comment]
Hmmm, maybe the console is constantly spitting stuff, the discord issue? this is from Unity so I doubt it's a bug on the actual close event. Let's review after the Discord error spamming issue is fixed.

**Comment by Kaytila** [comment]
ah, good point, had not thought of that.

**Comment by slashman** [comment]
Probably fixed by #2
