### ISSUE TITLE
Town screen: "Take" appears not to work, "Trade" does not open UI

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#18]
Town screen: "Take" appears not to work, "Trade" does not open UI

Test script:

1. Go to hut
2. select join
3. try to select take - nothing happens
4. try barter -> works
5. select trade -> Town UI disappears, you need to press options menu (not ESC, does not work) and re-enter
<img width="1318" alt="2021-05-20 20_25_04-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119029920-8a8c6380-b9a9-11eb-95f2-80e44d1a9fbb.png">

[Saves.zip](https://github.com/slashware/NovaMundiTracker/files/6524540/Saves.zip)

**Comment by slashman** [comment]
What size of town was this?  there should no longer be "Barter", only "Trade" (taking the player to the barter screen)

**Comment by Kaytila** [comment]
now with screenshot.

**Comment by slashman** [comment]
Is this 100% repro for you? I just trie it and it worked fine.

**Comment by Kaytila** [comment]
Yes, this is a save game.
100% repro for me, I did three or four times.

**Comment by slashman** [comment]
There's currently no support for save-game compatibility from older versions. I don't think we are at a point where we should add it, but at least we could display a message or block loading old saves games completely.

**Comment by Kaytila** [comment]
alright, I attached the save game for trying out if you want to clarify.
But yes, you should block loading old saves in case this makes things difficult.

**Comment by Stoltverd** [comment]
Can't be reproduced
