### ISSUE TITLE
Ramiriqui - initial dialog missing keyword

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#19]
see screenshot.
<img width="1360" alt="2021-05-21 21_00_09-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119185916-aeb67600-ba77-11eb-9199-6f3a4162f448.png">

**Comment by slashman** [comment]
Deciding how to tackle this, Muysccubun words might end up having a tooltip feature so you can see the translation in whatever your language is. But until that is in (need to transition to TextMeshPro), may just add them as normal keyword.

**Comment by Stoltverd** [comment]
Tooltip feature was implemented several versions ago.
