### ISSUE TITLE
Discord issue spamming logfile

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#2]
NullReferenceException: Object reference not set to an instance of an object
  at DiscordController.Update () [0x00007] in C:\git\expedition2\Assets\Plugins\Discord\DiscordController.cs:35 
 
(Filename: C:/git/expedition2/Assets/Plugins/Discord/DiscordController.cs Line: 35)

**Comment by slashman** [comment]
I guess you didn't have discord open? just confirming.

**Comment by Kaytila** [comment]
I only use discord in the browser, not as separate application.
This spams (spam spam humbug)  permanently.

**Comment by slashman** [comment]
EX-2200 created

**Comment by slashman** [comment]
Fixed for v0.26.1
