### ISSUE TITLE
Trade Screen - Reset on Merchant side does not work

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#20]
<img width="1633" alt="2021-05-21 21_16_41-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119187786-18d01a80-ba7a-11eb-83b7-8f198b10ee32.png">
test script:

1. go to town
2. go to merchant
3. add anything from their wares
4. press reset
5. reset will not work on their side

it does however work on the player's party side.

**Comment by slashman** [comment]
Fixed for v0.26.1
