### ISSUE TITLE
party screen - use item on member issues

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#22]
so if you select a party member first and then try to find the item - the party member is not highlighted.
Also, you cannot de-select the party member, you need to leave the screen first.

**Comment by slashman** [comment]
Will be addressed with the status screen revamp.

**Comment by slashman** [comment]
Highlight party member: Fixed for v0.27.0
Being able to deselect party member: Why would this be needed?

**Comment by slashman** [comment]
Not being able to deselect is being discussed in #41
