### ISSUE TITLE
combat: archers useless with a party of 40

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#34]
if you have a party of 40 people, 10 tanks, 10 DDs, 5 explorer and 15 archers, the archers normally do not even get in range before everyone of the enemy is dead.
Also, ranged damage is still nothing compared to the melee DD, that applies to both the spanish and the muisca.

**Comment by slashman** [comment]
This must be addressed, but I'm still deciding how.

I am considering putting a cap on party size so you cannot have 40, for instance. More like max 20 or something like that.

**Comment by slashman** [comment]
Also considering less rigid balancing options. In any case this will be addressed in the upcoming combat-centered iteration.

**Comment by Kaytila** [comment]
Two things come to mind:

1. In a hut with population of 20  - i.e. extended family - how should there be more than one or two person available for joining?
Randomness is fine, but I would say rand.nextInt(2) is fine as a cap there.
As for cities or larger settlements - if a group of people comes joining, it strikes me as odd that some are unwilling to come right away but can be talked into with stories (i.e. spend experience points). I know that is probably the idea, but perhaps limit this as well?

2. if you want to go into manning camps (7 cities of gold again) - then having a huge party for a time might actually be a necessity, even more so if you want to leave injured people camped.

Generally, my experience right now is if you get one or two settlements in the first two days, then you have an overwhelming amount of DDs who will finish off any opponent very fast, especially if they have a range+ blessing on them.
This ties directly back to archers: a DD with a range extension blessing will kill any enemy before the archer gets his bow drawn and ready.

**Comment by slashman** [comment]
Hopefully addressed in v0.26.3 https://store.steampowered.com/news/app/1370940/view/3029213301437043874
