### ISSUE TITLE
Overland map - swim/wade behaviour

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#37]
My understanding is that the first person in the group decides the terrain of the rest.
This is fine for now I think but:
Then my expectation is that when I am done wading through a river with the leading person, that the movement speeds up right away again and not until the third person.
<img width="617" alt="2021-05-27 09_01_04-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119780615-5396e000-beca-11eb-9806-39edc93814ab.png">

**Comment by slashman** [comment]
The problem here is actually a lack of precision with the underlying "logic" map of biomes. I think for rivers it will make more sense to check vs height :/

**Comment by Stoltverd** [comment]
Should be fixed by next week!
*Famous last words*
