### ISSUE TITLE
Camp dialog - first time translation missing ?

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#38]
when you camp for the first time, the dialog looks like this, it appears it doesnt find the translations then?
<img width="468" alt="2021-05-27 09_20_13-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119782781-e173ca80-becc-11eb-97fd-e5ca6b0e66c7.png">

**Comment by Stoltverd** [comment]
Finally working on it!
Thanks!
