### ISSUE TITLE
Overland - Movement against blocked paths

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#39]
So it is possible to move against i.e. a town or villages and the party will continue running against the block and time will pass.
<img width="447" alt="2021-05-27 09_27_42-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119792286-dec9a300-bed5-11eb-9b05-61a9408f19df.png">

**Comment by Stoltverd** [comment]
This was also reported internally. This means it's currently a duplicate.
Closing this for now.
