### ISSUE TITLE
party screen: position of name and type

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#40]
So I always always mix up the people due to the fact that type and name are aligned to the bottom of the tile.
I would prefer to see this up at the top instead.
<img width="319" alt="2021-05-27 10_27_33-NovaMundi" src="https://user-images.githubusercontent.com/18169955/119792875-5b5c8180-bed6-11eb-943c-f8c6b3a06a7c.png">

**Comment by slashman** [comment]
As mentioned in #22, this screen is going to change with a smaller version of the units, I'll keep these suggestions in mind tho they may look a bit different.

**Comment by Kaytila** [comment]
Do you have a design for that already?

**Comment by slashman** [comment]
Please evaluate in v0.27.0

**Comment by Kaytila** [comment]
Much much better, awesome!
