### ISSUE TITLE
Inventory Screen: not able to de-select item

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#41]
test script:

open inventory
select item
click on item again - this should de-select in my opinion
stays selected.
click outside of any item - this should also de-select
stays selected.

**Comment by slashman** [comment]
Why do we need to unselect items?

**Comment by Kaytila** [comment]
It strikes me as odd that you cannot as this is a kind of standard metaphor in that kind of listview interface.

**Comment by Stoltverd** [comment]
Not a bug, but work is being done to implement the suggested behavior. Thanks!
