### ISSUE TITLE
food calculation - overland map vs trade screen vs calculation?

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#44]
so on the next game - could not load my save game due to the error message, very good - I traded a blessing for 25 bandages or so and 250 units of food.
I could do this, but somehow the calculation/depiction of "food left" is off, see screenshots - trade screen shows 3 days, overland map shows 1 day for food.

also: there are 16 people in the party.
As far as I understood the rules, <party members>*3 == 1 day of food.
there are 381 units of maize:

381 // 48 == 7 days.

So, something is definitely off.

<img width="1672" alt="2021-05-28 22_05_52-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120037109-652ed380-c001-11eb-9058-da3221b59a28.png">

**Comment by slashman** [comment]
* These Maize rations expire in 3 days, thus cannot be used afterward (the 3 days calculation is fine)
* The bar in the background is indeed not being updated properly (EX-2231 created)
* Should probably make more visible somewhere that you are acquiring more food than you'll be able to use. (EX-2322 created)

**Comment by slashman** [comment]
Fixed for v0.26.3+
