### ISSUE TITLE
party screen overlap when getting people from settlement

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#45]
party screen overlap when getting people from settlement

<img width="671" alt="2021-05-28 22_18_46-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120037947-c30feb00-c002-11eb-8d4c-c22d72945845.png">

**Comment by slashman** [comment]
Was already in as EX-2198, fixed for v0.26.3+
