### ISSUE TITLE
Barter - shift-click to match

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#46]
Test script:

request 2 bandages
shift click on Maize,
120 are selected.
121 are needed:
<img width="924" alt="2021-05-31 11_22_54-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120171686-97f3ea00-c202-11eb-80c6-fe5f433f3f60.png">
<img width="812" alt="2021-05-31 11_22_46-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120171694-9a564400-c202-11eb-8d04-2ceb193f32a4.png">

**Comment by Kaytila** [comment]
Version 0.31 - still possible to achieve this:
Steps to reproduce:

start game, go to merchant
offer 3 tejuelos
click on bandages
8 bandages are selected, but the merchant is unhappy.

if you select 2 tejuelos, you get 5 bandages + 16 food and all is well

**Comment by Kaytila** [comment]
Version 0.31: additional case:

1. offer 3 tejuelos
2. select bandages, you get 8 -> merchant is not happy
3. reduce by one, you get 7 --> merchant happy.
4. shift-click on food, you get 50 --> merchant is not happy
5. reduce to 49 --> merchant happy

**Comment by Stoltverd** [comment]
Can still be reproduced. 
Moved the issue to our weekly board and will be closed for now so we can organize the in-house reports, with these public reports.
