### ISSUE TITLE
inventory - de-selecting items appears not to work at least visually

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#5]
test script:

1. go  to inventory screen
2. left click and item to select it, it will be highlighted
3. left clicking again on it will not de-select
4. clicking on a second item will also highlight it

applying to a unit will only apply the second selected item. so the backend works fine, just the selection in the UI does not.

**Comment by slashman** [comment]
EX-2199

**Comment by slashman** [comment]
Fixed in v0.26.0
