### ISSUE TITLE
burdened calculation

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#53]
So my party is at 82% capacity - does this really count as burdened?
<img width="1613" alt="2021-06-01 14_44_20-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120325462-f2b34180-c2e7-11eb-8e0b-8752fdf539ff.png">

**Comment by slashman** [comment]
Yes, > 80% is burdened. This reminds me I need to create a wiki with all the rules

**Comment by Kaytila** [comment]
Yes, at least for player testers to compare and check :D

**Comment by slashman** [comment]
#54 created as follow up
