### ISSUE TITLE
Biome calculation a little off now

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#55]
see screenshot - I would not assume this to be forest.
<img width="1024" alt="2021-06-02 22_47_26-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120550060-ad306a80-c3f4-11eb-9add-f711aec976d1.png">

**Comment by Kaytila** [comment]
Also, it appears that the biome graphics to the lower right vs the textual representation to the upper left are kind of not synchronized completely, see screenshot.
![2021-06-03 13_01_32-NovaMundi](https://user-images.githubusercontent.com/18169955/120634969-2fa84100-c46c-11eb-8d4c-ed4927c221b0.gif)

**Comment by Kaytila** [comment]
Hmmm, so let me be more precise, the dark patch is recognized as forest - which is fine after your explanation, but
look at the zoom level: it is mid-day and its zoomed in as if the party were in the forest but definitely is not. Party also moves with reduced speed.
<img width="842" alt="2021-06-03 22_32_43-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120708440-dc5ddf00-c4bb-11eb-8f05-cd82bedb4bea.png">

**Comment by Kaytila** [comment]
So party walked towards the left and was walking slowly - the guecha is the party leader currently.

**Comment by slashman** [comment]
Fixed in v0.28.1
