### ISSUE TITLE
journal entries: text appears to contain wrong location information

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#59]
the text here strikes me as odd, so I am at Paipaquira's Hut, why am I near Onza?
<img width="499" alt="2021-06-03 13_51_05-NovaMundi" src="https://user-images.githubusercontent.com/18169955/120640526-dee81680-c472-11eb-8f86-c502e993b576.png">

**Comment by slashman** [comment]
Might be related to #28

**Comment by slashman** [comment]
Fixed in v0.28.2+
