### ISSUE TITLE
party screen - ideas and issues

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#6]
I so like the new party member screen when you are in towns - you can now really see the difference where people begin and end so to speak.
This is missing in the "party screen" (I).
Also, you now see that people are ill - It is still hard to see whether they are curing or indisposed. 
That is why I would prefer the health bar colours to change. I.e
dark red: all good - no effects in place. stays that way until drop below 50% health.
dark green: sick/poisoned/injured
yellow: health is below 50%
orange: health aid applied
light green: medicine for green condition applied.

Also, general topic: how about making the portraits a little bit smaller?

How about grouping the people? I have made a quick pencil drawing below what i mean.
6 people per line and groupings around different types.

I can see that people can gain experience in the battles, but do i see anywhere how far they are?
do i see what the difference is between a level 1 guardian and a level 3 guardian?
I would like to be able to see that somehow, either on mouse over which might become too filled up, or a separate "party member properties dialogue" so to speak.

**Comment by Kaytila** [comment]
![nova_mundi_party_screen_proposal](https://user-images.githubusercontent.com/18169955/118106217-a7d79580-b3dd-11eb-8ab2-48dac9ca572a.png)

**Comment by slashman** [comment]
- Replicate the appearance of the party member on the TransferItems UI into the Expedition Status UI, including smaller portraits and defined borders
Actually, that is what the UI designer had in mind, the current Expedition Status UI is something I came up with, wanting the units to have more protagonism (hence the bigger portraits). I guess that may make more sense if the party was smaller and more unique and there was less rotation. I think I'll fall back to a more compressed view.
- Use health bar colors as an indicator of illness
Yes
- Use health bar colors as an indicator of recovery item applied
Not sure about it, was thinking instead displaying the icon of the recovery item next to the unit (i.e. the bandage or medicinal herb)
- Use health bar colors as an indicator of low health
Not sure, might want to reserve the color code for different status effects?
- Group people per unit type
Yes, we had something similar in the past for other screens, and makes sense now that you have a lot of units.
- Display unit experience in Unit Detail popup
Yes, we have a Unit Detail popup planned, I think we should up the priority for it.

**Comment by Kaytila** [comment]
> Actually, that is what the UI designer had in mind, the current Expedition Status UI is something I came up with, wanting the units > to have more protagonism (hence the bigger portraits). I guess that may make more sense if the party was smaller and more unique and there was less rotation. I think I'll fall back to a more compressed view.

Ah, I understand - so RPG party is what you had in mind now, but with 50 people its way beyond that.

>Not sure about it, was thinking instead displaying the icon of the recovery item next to the unit (i.e. the bandage or medicinal >herb)

Yes, that actually sounds like a better idea!

> Not sure, might want to reserve the color code for different status effects?

Healing/recovering is also a status effect, isnt it?
But you are right, using normal red and yellow just as percentage indicators would break the color code and mix up different pieces of information.
I guess it depends on how many effects there are going to be?
I can think of the following:
- tired <-- probably stays handled on party level, not individually
- hungry <-- probably stays handled on party level, not individually
- asleep/unconscious
- poisoned
- injured <-- healed through different items perhaps than poison?
- feared
- enraged

the latter two might be interesting if you decide to work on that bonding element more.
You know, person gets enraged if buddy gets injured, or feared if buddy gets injured, something like that.

**Comment by slashman** [comment]
* Replicate the appearance of the party member on the TransferItems UI into the Expedition Status UI, including smaller portraits and defined borders - DONE
* Use health bar colors as an indicator of illness - PENDING
* Group people per unit type - PENDING (However we are sorting already)
* Display unit experience in Unit Detail popup - PENDING

**Comment by Stoltverd** [comment]
Not a bug.
