### ISSUE TITLE
Clicking in caves or combat with no unit selected displays the moving cursor

### ISSUE THREAD

**Issue by jucarave** [slashware/NovaMundiTracker#60]
When clicking around to give orders to units inside combat or a cave, the game displays the action icon leading to some confusion since no unit will perform that action.

![image](https://user-images.githubusercontent.com/8118259/121791690-36446000-cbb2-11eb-8e6f-d5bddb886c5a.png)
![image](https://user-images.githubusercontent.com/8118259/121791691-393f5080-cbb2-11eb-9d5b-b9153d5a107b.png)

**Comment by Stoltverd** [comment]
Will be fixed by @slashman soon.
