### ISSUE TITLE
Combat: Spacebar useage

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#61]
So pressing space pauses the combat.
Second space opens inventory.
I would assume that third space (after escing out of inventory) would start combat again.
But it starts again after closing the inventory.

I think that is wrong. I would prefer - 
space - toggles combat pause on or off
I - inventory

**Comment by slashman** [comment]
This is actually buggy behavior. Space should toggle pause on and off, shouldn't trigger inventory,

**Comment by Stoltverd** [comment]
How pause works in combat changed by design.
If the new behavior is perceived as a bug, please do report again.
