### ISSUE TITLE
Combat: Unit selection accuracy

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#62]
So I tried to play around with unit  movement in combat.
It is very hard to actually hit a unit. 
See screenshot, I am clicking on the enemy - see mouse cursor.
And see where the "location pointer" is.

<img width="571" alt="2021-06-20 13_19_02-NovaMundi" src="https://user-images.githubusercontent.com/18169955/122672117-2f2cdb80-d1ca-11eb-977d-eaa9a937eaf2.png">

**Comment by slashman** [comment]
Fixed on v0.29.1+
