### ISSUE TITLE
Journal and Objectives are not in sync

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#70]
After talking to Aquachen in Garagoca, the journal is not updated.
The mission objectives however are.

To Reproduce Steps to reproduce the behavior:

enter Garagoca
talk to Aquachen 
click on invaders and follow the dialogue tree.
leave the city.
press "J", you will not see an additional entry.
click on mission objectives - you will see the mission entry.

Screenshots If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

Additional context Add any other context about the problem here.
<img width="788" alt="2023-02-19 21_59_29-NovaMundi" src="https://user-images.githubusercontent.com/18169955/220076122-a00d4c23-8ad8-41cc-a157-9e550f8e3c6d.png">

**Comment by slashman** [comment]
There are two bugs here,
- One about the journal being neglected, I've fixed it for this quest but added the task to do the same for the remaining main and sidequests.
- A missing translation, probably from a discovery, that one is still pending.

**Comment by slashman** [comment]
Removed invalid journal description for settlements.

**Comment by slashman** [comment]
Fixed for 0.38.3
