### ISSUE TITLE
Munquira quest - dialog tree issue

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#71]
when you talk to munquira about help, there are two options:
"i will help'" - "i do not have time".
If you click on "i will help", the quest flag is set (see missions), but you still have the "deny" option available.
<img width="1521" alt="2023-02-20 11_03_24-NovaMundi" src="https://user-images.githubusercontent.com/18169955/220076964-37e43a93-ed7d-4436-b084-e1c8ec5a5dc4.png">

**Comment by slashman** [comment]
xorGroups are broken.

**Comment by slashman** [comment]
Fixed for v0.38.3
