### ISSUE TITLE
Shop - rounding is slightly off

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#72]
when shift clicking on items, the rounding is a little off sometimes:

steps to reproduce:
1. start game
2. go to merchant
3. offer puma and one tejuelo
4. shift click on bandages
5. you will see an unhappy face
(addition)
6. reduce one bandage
7. shift click on corn -> unhappy face again
8. reduce corn by one -> happy face
expected result: shift clicking always should lead to a valid proposal.
If you have offered 5000 value , but one bandage is worth 400, offer 12 (=4800), but not 13 (=5200).

shift clicking on corn to fill up the gap is valid, although a newbie hint "It looks like the merchant would be willing to give you something else for your valuables" would be nice.

<img width="1511" alt="2023-02-20 11_19_13-NovaMundi" src="https://user-images.githubusercontent.com/18169955/220078100-f3ec39e6-e474-4631-9f5c-597045123b76.png">

**Comment by slashman** [comment]
Fixed for 0.38.3
