### ISSUE TITLE
shop - shop owner dialog in Suamox shows {overburden}

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#73]
The shop owner in Suamox only shows {overburden} .

**To Reproduce**
1. go to suamox
2.  visit the merchant
3. look at the dialog area
4. offer items
5. request items

the dialog does not refresh, you do not have any idea what is going on.

the standard dialog should be shown here.

<img width="590" alt="2023-02-20 11_30_09-NovaMundi" src="https://user-images.githubusercontent.com/18169955/220080899-d07a2151-82c8-4b69-91ca-12490752e7b7.png">

**Comment by slashman** [comment]
There are two bugs here, the missing message and the fact that the burden bar doesn't update after the first barter.

**Comment by slashman** [comment]
Additionally, a dialog display if you try to trade and cannot carry.

Thanks for the report!

**Comment by slashman** [comment]
Fixed for v0.38.3
