### ISSUE TITLE
World creation: river looks somewhat odd

### ISSUE THREAD

**Issue by Kaytila** [slashware/NovaMundiTracker#8]
the way the river flows kind of reminds me heart of africa, only more modern in looks:
![image](https://user-images.githubusercontent.com/18169955/118144061-4da1f900-b40c-11eb-9ac7-66d7f620704a.png)

**Comment by slashman** [comment]
Newest versions removed the "foam" so it blends a liiiitle big more, we should check back and evaluate, but in any case, this is caused due to the low resolution of the terrain, the "thin" width of rivers, and the uniform height of the riverbanks, so there's room to improve.

**Comment by Kaytila** [comment]
I think it looks much better without the river foam.

**Comment by slashman** [comment]
will work on this further with varying river width, and adornments on its borders.

**Comment by Stoltverd** [comment]
Regarding foam, this was changed. Regarding the shape... it's difficult.
Closing as not planned for now, but we are discussing it internally to decide when to tackle the aesthetics of the rivers.
